"""Extracts the dice numeral glyphs (0-9 and the period) from Inter Regular
into `lib/dice_glyphs.g.dart` as flattened outline polygons.

Inter is the look-dev's numeral font (docs/design/dice-lookdev.md: Inter at
its regular weight, bundled with Blender; SIL Open Font License 1.1, see
`OFL-Inter.txt`). The Dart side (`dice_numerals.dart`) rasterizes these
outlines into the dice atlases at runtime, so the app carries no font or
image asset for its numerals.

Run (fontTools + brotli, for the woff2 container):

    uv run --with fonttools --with brotli python \
        dart3d/example/tool/dice_glyphs/extract_glyphs.py \
        [path/to/Inter.woff2]

The default path is Blender's bundled copy, which is what the look-dev
renders used. Its cmap maps the digits to the tabular figures with the
open 4 / straight-tailed 6 and 9 (`four.tf.ss01`, ...): kept as-is.
"""

import glob
import sys
from pathlib import Path

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / "lib" / "dice_glyphs.g.dart"
CHARS = "0123456789."
STEPS = 6  # line segments per quadratic curve


class FlattenPen(BasePen):
    def __init__(self, glyphset):
        super().__init__(glyphset)
        self.contours = []
        self.cur = None

    def _moveTo(self, p):
        self.cur = [p]

    def _lineTo(self, p):
        self.cur.append(p)

    def _qCurveToOne(self, p1, p2):
        p0 = self.cur[-1]
        for i in range(1, STEPS + 1):
            t = i / STEPS
            a, b, c = (1 - t) ** 2, 2 * (1 - t) * t, t * t
            self.cur.append((a * p0[0] + b * p1[0] + c * p2[0], a * p0[1] + b * p1[1] + c * p2[1]))

    def _curveToOne(self, p1, p2, p3):
        p0 = self.cur[-1]
        for i in range(1, STEPS + 2):
            t = i / (STEPS + 1)
            a, b, c, d = (1 - t) ** 3, 3 * (1 - t) ** 2 * t, 3 * (1 - t) * t * t, t ** 3
            self.cur.append((a * p0[0] + b * p1[0] + c * p2[0] + d * p3[0],
                             a * p0[1] + b * p1[1] + c * p2[1] + d * p3[1]))

    def _closePath(self):
        if self.cur and self.cur[0] == self.cur[-1]:
            self.cur.pop()
        self.contours.append(self.cur)
        self.cur = None

    _endPath = _closePath


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else glob.glob(
        "/Applications/Blender.app/Contents/Resources/*/datafiles/fonts/Inter.woff2")[0]
    font = TTFont(path)
    upem = font["head"].unitsPerEm
    cap = font["OS/2"].sCapHeight
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    lines = [
        "// GENERATED by tool/dice_glyphs/extract_glyphs.py — do not edit.",
        "// Inter Regular (SIL Open Font License 1.1; tool/dice_glyphs/OFL-Inter.txt):",
        f"// {font['name'].getDebugName(5)}.",
        "// Outlines in font units (y up), quadratics flattened to "
        f"{STEPS} segments.",
        "library;",
        "",
        f"const int kGlyphUnitsPerEm = {upem};",
        "",
        "/// Cap height (the digits' height) in font units.",
        f"const int kGlyphCapHeight = {cap};",
        "",
        "/// char → (advance width, contours as flat x,y lists).",
        "const Map<String, (int, List<List<double>>)> kDiceGlyphs = {",
    ]
    for ch in CHARS:
        name = cmap[ord(ch)]
        pen = FlattenPen(gs)
        gs[name].draw(pen)
        adv = font["hmtx"][name][0]
        contours = []
        for c in pen.contours:
            flat = ", ".join(f"{x:.1f}, {y:.1f}" for x, y in c)
            contours.append(f"    [{flat}],")
        key = "'.'" if ch == "." else f"'{ch}'"
        lines.append(f"  {key}: ({adv}, [")
        lines.extend(contours)
        lines.append("  ]),")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
