// W7 environment/IBL checks: the `stage.environmentRef` →
// `kind:'environment'` resource encoding, the `updateStage` command op
// `diffCommands` emits on `stageChanged`, and the payload-environment
// chunk wiring — pinned by docs/environment-ibl-spec.md. Same
// constraint as the W3–W5 tests: package:dart3d/dart3d.dart is
// unreachable under `dart test` (the barrel transitively imports
// package:dartnative, which needs DartNative's patched SDK), so this
// pulls the pure-Dart libraries directly and exercises `diffCommands`
// — `SceneController.applyDiff` is a thin wrapper over it. The
// equirect PNG the harness's env-3 lane embeds is reproduced here with
// the same `package:image` recipe that generated it (the app can't
// import image — its PNG encoder pulls in package:archive, which
// DartNative's SDK shadows — so the generated bytes are embedded).
// ignore_for_file: implementation_imports

import 'dart:convert';
import 'dart:typed_data';

import 'package:dart3d/src/diff_apply.dart';
import 'package:dart3d/src/scene_model.dart';
import 'package:image/image.dart' as img;
import 'package:test/test.dart';
import 'package:vector_math/vector_math.dart';

void main() {
  // Deterministic ids — explicit (session, index) pairs so tokens are
  // stable across documents and expected shapes can name them.
  const envId = LocalId(1, 20);
  const nodeId = LocalId(1, 30);
  const chunkId = LocalId(1, 40);

  /// The baseline look every harness lane shares — only the sealed
  /// `environment` member varies (docs/environment-ibl-spec.md). The
  /// W13 lanes also vary `effects`/`overridesEffects`.
  EnvironmentResource envResource(
    LocalId id,
    EnvironmentSpec environment, {
    EnvironmentEffectsSpec? effects,
    bool overridesEffects = true,
  }) => EnvironmentResource(
    id,
    environment: environment,
    environmentIntensity: 1.0,
    exposure: 1.0,
    toneMapping: 'pbrNeutral',
    skybox: SkyboxSpec(EnvironmentSkySpec()),
    effects: effects,
    overridesEffects: overridesEffects,
  );

  /// The feature_scene env-3 payload recipe: a 64×32 LDR equirect —
  /// bright sky-blue top third, green horizon band, dark-brown bottom
  /// third, plus a bright yellow sun spot so orientation reads in
  /// reflections — encoded as PNG by `package:image`.
  Uint8List equirectPng() {
    const w = 64;
    const h = 32;
    final image = img.Image(width: w, height: h);
    for (var y = 0; y < h; y++) {
      for (var x = 0; x < w; x++) {
        if (y * 3 < h) {
          image.setPixelRgb(x, y, 90, 165, 255);
        } else if (y * 3 < 2 * h) {
          image.setPixelRgb(x, y, 60, 165, 70);
        } else {
          image.setPixelRgb(x, y, 62, 42, 26);
        }
      }
    }
    const cx = 44;
    const cy = 5;
    const r = 3.0;
    for (var y = 0; y < h; y++) {
      for (var x = 0; x < w; x++) {
        final dx = x - cx;
        final dy = y - cy;
        if (dx * dx + dy * dy <= r * r) {
          image.setPixelRgb(x, y, 255, 235, 40);
        }
      }
    }
    return img.encodePng(image);
  }

  group('environment manifest', () {
    test(
      'studio EnvironmentResource + stage.environmentRef encode per spec',
      () {
        final doc = SceneDocument();
        doc.addResource(envResource(envId, const StudioEnvironment()));
        doc.stage.environmentRef = envId;

        final manifest = jsonDecode(writeFscene(doc)) as Map<String, dynamic>;
        expect(manifest['stage'], {'environmentRef': 'env:${envId.toToken()}'});

        final resources = manifest['resources'] as Map<String, dynamic>;
        final entry =
            resources['env:${envId.toToken()}'] as Map<String, dynamic>;
        expect(entry['kind'], 'environment');
        expect(entry['environment'], {'type': 'studio'});
        expect(entry['environmentIntensity'], 1.0);
        expect(entry['exposure'], 1.0);
        expect(entry['toneMapping'], 'pbrNeutral');
        expect(entry['skybox'], {
          'source': {'type': 'environment', 'blurriness': 0.0},
          'intensity': 1.0,
        });

        // Full round-trip: the manifest decodes back to the same wiring.
        final back = readFscene(writeFscene(doc));
        expect(back.stage.environmentRef, envId);
        final backEnv = back.resources[envId]! as EnvironmentResource;
        expect(backEnv.environment, isA<StudioEnvironment>());
        expect(backEnv.skybox!.source, isA<EnvironmentSkySpec>());
      },
    );

    test('the constant and empty environment members encode per spec', () {
      Map<String, dynamic> envEntry(EnvironmentSpec environment) {
        final doc = SceneDocument();
        doc.addResource(envResource(envId, environment));
        doc.stage.environmentRef = envId;
        final manifest = jsonDecode(writeFscene(doc)) as Map<String, dynamic>;
        return (manifest['resources']
                as Map<String, dynamic>)['env:${envId.toToken()}']
            as Map<String, dynamic>;
      }

      // Vector3 stores f32 — assert the values within f32 epsilon
      // rather than the literal doubles.
      final constant =
          envEntry(
                ConstantEnvironment(Vector3(0.25, 0.18, 0.12)),
              )['environment']
              as Map<String, dynamic>;
      expect(constant['type'], 'constant');
      expect((constant['color'] as List).cast<double>(), [
        closeTo(0.25, 1e-6),
        closeTo(0.18, 1e-6),
        closeTo(0.12, 1e-6),
      ]);
      expect(envEntry(const EmptyEnvironment())['environment'], {
        'type': 'empty',
      });
    });
  });

  group('updateStage op', () {
    /// A document whose only variable is `stage.environmentRef` — the
    /// resource pool, nodes, and payloads are identical either way.
    SceneDocument staged(LocalId? ref) {
      final doc = SceneDocument();
      doc.addResource(envResource(envId, const StudioEnvironment()));
      doc.stage.environmentRef = ref;
      doc.addNode(
        NodeSpec(id: nodeId, name: 'anchor', transform: TrsTransform()),
        root: true,
      );
      return doc;
    }

    test('a stage-only diff emits exactly one updateStage op', () {
      final a = staged(null);
      final b = staged(envId);
      final diff = diffScene(a, b);
      expect(diff.stageChanged, isTrue);
      final ops = diffCommands(diff, a, b);
      expect(ops, hasLength(1));
      expect(ops.single, {
        'op': 'updateStage',
        'stage': {'environmentRef': 'env:${envId.toToken()}'},
      });
    });

    test('updateStage lands after node ops in a mixed batch', () {
      final a = staged(null);
      final b = staged(envId);
      b.addNode(
        NodeSpec(
          id: const LocalId(2, 1),
          name: 'added',
          transform: TrsTransform(),
        ),
        root: true,
      );
      final ops = diffCommands(diffScene(a, b), a, b);
      expect([for (final o in ops) o['op']], ['addNode', 'updateStage']);
    });

    test('an identical stage emits no updateStage op', () {
      final a = staged(envId);
      final b = staged(envId);
      expect(diffCommands(diffScene(a, b), a, b), isEmpty);
    });
  });

  // W13: the env resource's `effects` block — absolute-replacement
  // semantics on the wire, `overridesEffects` gating the key, and the
  // upsertResource + updateStage pair a content-only env edit emits.
  group('environment effects', () {
    /// The staged() shape with an effects spec attached — node,
    /// resource pool and stage ref identical either way.
    SceneDocument stagedEffects(
      EnvironmentEffectsSpec? effects, {
      bool overridesEffects = true,
    }) {
      final doc = SceneDocument();
      doc.addResource(
        envResource(
          envId,
          const StudioEnvironment(),
          effects: effects,
          overridesEffects: overridesEffects,
        ),
      );
      doc.stage.environmentRef = envId;
      doc.addNode(
        NodeSpec(id: nodeId, name: 'anchor', transform: TrsTransform()),
        root: true,
      );
      return doc;
    }

    /// The manifest `resources` entry for the env resource.
    Map<String, dynamic> envEntry(
      EnvironmentEffectsSpec? effects, {
      bool overridesEffects = true,
    }) {
      final manifest =
          jsonDecode(
                writeFscene(
                  stagedEffects(effects, overridesEffects: overridesEffects),
                ),
              )
              as Map<String, dynamic>;
      return (manifest['resources']
              as Map<String, dynamic>)['env:${envId.toToken()}']
          as Map<String, dynamic>;
    }

    test('an effects-only env edit emits upsertResource + updateStage', () {
      final a = stagedEffects(null);
      final b = stagedEffects(
        EnvironmentEffectsSpec(
          bloomEnabled: true,
          bloomIntensity: 0.4,
          bloomThreshold: 0.8,
        ),
      );
      final ops = diffCommands(diffScene(a, b), a, b);
      expect([for (final o in ops) o['op']], ['upsertResource', 'updateStage']);
      // The resource op names the env id and carries the encoded
      // block; the stage re-ships the same environmentRef.
      expect(ops.first['id'], 'env:${envId.toToken()}');
      expect((ops.first['resource'] as Map)['effects'], {
        'bloom': {'enabled': true, 'threshold': 0.8, 'intensity': 0.4},
      });
      expect(ops.last, {
        'op': 'updateStage',
        'stage': {'environmentRef': 'env:${envId.toToken()}'},
      });
    });

    test('overridesEffects gates the wire effects key', () {
      // Overrides on + defaults: the (empty) block still emits — the
      // W13 reset step relies on `effects:{}` clearing every family.
      expect(envEntry(null)['effects'], isEmpty);
      expect(envEntry(EnvironmentEffectsSpec(bloomEnabled: true))['effects'], {
        'bloom': {'enabled': true},
      });
      // Overrides off drops the key even with authored values, and the
      // decoder derives overridesEffects from the key's presence.
      expect(
        envEntry(
          EnvironmentEffectsSpec(bloomEnabled: true),
          overridesEffects: false,
        ).containsKey('effects'),
        isFalse,
      );
      final back = readFscene(
        writeFscene(
          stagedEffects(
            EnvironmentEffectsSpec(bloomEnabled: true),
            overridesEffects: false,
          ),
        ),
      );
      final backEnv = back.resources[envId]! as EnvironmentResource;
      expect(backEnv.overridesEffects, isFalse);
      expect(backEnv.effects.bloomEnabled, isFalse);
    });

    test('the overridesEffects flip alone re-emits the env resource', () {
      final a = stagedEffects(null);
      final b = stagedEffects(null, overridesEffects: false);
      final ops = diffCommands(diffScene(a, b), a, b);
      expect([for (final o in ops) o['op']], ['upsertResource', 'updateStage']);
      expect(ops.first['id'], 'env:${envId.toToken()}');
      expect((ops.first['resource'] as Map).containsKey('effects'), isFalse);
    });
  });

  group('payload environment', () {
    test(
      'the equirect chunk lists in payloads and the resource points at it',
      () {
        final png = equirectPng();
        final doc = SceneDocument();
        doc.addPayload(
          PayloadSpec(
            chunkId,
            encoding: PayloadEncoding.image,
            format: 'png',
            width: 64,
            height: 32,
            length: png.lengthInBytes,
            bytes: png,
          ),
        );
        doc.addResource(envResource(envId, PayloadEnvironment(chunkId)));
        doc.stage.environmentRef = envId;

        final manifest = jsonDecode(writeFscene(doc)) as Map<String, dynamic>;
        final payloadKey = 'chunk:${chunkId.toToken()}';
        final payloads = manifest['payloads'] as Map<String, dynamic>;
        expect(payloads.keys, contains(payloadKey));
        expect(payloads[payloadKey], {
          'encoding': 'image',
          'format': 'png',
          'width': 64,
          'height': 32,
          'length': png.lengthInBytes,
        });
        final entry =
            (manifest['resources']
                    as Map<String, dynamic>)['env:${envId.toToken()}']
                as Map<String, dynamic>;
        expect(entry['environment'], {
          'type': 'payload',
          'payload': payloadKey,
        });
        expect(
          (manifest['stage'] as Map)['environmentRef'],
          'env:${envId.toToken()}',
        );
      },
    );

    test('the generated equirect decodes to the spec band layout', () {
      final image = img.decodePng(equirectPng())!;
      expect(image.width, 64);
      expect(image.height, 32);
      List<num> rgb(int x, int y) {
        final p = image.getPixel(x, y);
        return [p.r, p.g, p.b];
      }

      expect(rgb(10, 3), [90, 165, 255]); // sky-blue top third
      expect(rgb(10, 16), [60, 165, 70]); // green horizon band
      expect(rgb(10, 28), [62, 42, 26]); // dark-brown bottom third
      expect(rgb(44, 5), [255, 235, 40]); // yellow sun spot
      expect(rgb(20, 5), [90, 165, 255]); // sky beside the spot
    });
  });
}
